print('What do you get when you cross a snowman with a vampire?'.upper())
print('Frostbite!'.lower())
print()
print()
print('What do dentists call a astronaut\'s cavity?')
print('A black hole!')
print()
print()
print('Knock knock.')
print("Who's there?")
print('Interrupting cow.')
print('Interrupting cow wh', end='')
print('-MOO!')
print()
print()
print('I invented a \nnew word!')
print('Plagiarism')
print()
print()
print("Why do we tell actors to \"break a leg?\"")
print('Because every play has a cast')
print()
print()
print('Did you hear about the actor\'s who fell through the floorboards?')
print('He was just going through a stage.')

