print('What do you get when you cross a snowman with a vampire?')
first_joke = input()
print('You said ' + first_joke, end = ' ')
print ('but it is Frostbite!')
print('What do dentists call a astronaut\'s cavity?')
input()
print('A black hole!')
# print() prints a blank line
print()
print('Knock knock.')
input()
print("Who's there?")
input()
print('Interrupting cow.')
input()
print('Interrupting cow wh', end='')
print('-MOO!')
